### PR TITLE
Allow each instance to have a public IP assigned via LC.

### PR DESCRIPTION
**Pull request by jasiek**

### CODE REVIEW

**Comment by tfhartmann** [comment]
Is there a particular reason to put this config here, rather then to rely on the VPC setting?

**Comment by jasiek** [comment]
I thought this was the right place to set it. I can't see an option to configure it on the VPC via terraform.

**Comment by tfhartmann** [comment]
No worries! Checkout out these links, they might help!  Here's athe TF docs, and https://www.terraform.io/docs/providers/aws/r/vpc.html#enable_dns_hostnames  here's an example of how the tf_aws_vpc module does it! https://github.com/terraform-community-modules/tf_aws_vpc/blob/master/main.tf#L4

**Comment by antonbabenko** [comment]
My 5 cents on this. While it is completely possible to follow the path @tfhartmann is describing I think it is a good (and backward-compatible) addition to the module which may bring benefits to other users as well. Let's merge when README is updated :)

**Comment by tfhartmann** [comment]
Let's also valodate that the default behavior is to continue using the setting inherited from the VPC.

**Comment by antonbabenko** [comment]
I was wrong that I thought this change was backward compatible because it really does not respect settings from VPC/subnet.

@tfhartmann What do you think if we merge this and cut a minor release (1.7.0)?

**Comment by tfhartmann** [comment]
@antonbabenko I think this should probably be a 2.0.0 release, since it's a breaking change.  For example when this is merged in, If you set you VPC to enable DNS hostnames, you'll have to override the module default to keep the current behavior.

**Comment by antonbabenko** [comment]
Agree

**Comment by tfhartmann** [comment]
@jasiek if you wouldn't mind updating the readme, we'll merge and cut a 2.0.0 version :)

**Comment by jasiek** [comment]
Will do.

**Comment by jasiek** [comment]
Done.

**Comment by jasiek** [comment]
Should we cut a release?

**Comment by tfhartmann** [comment]
Sure! I can do that shortly

**Pull request merged**
