### PR TITLE
Add elb option

### PR DESCRIPTION
**Pull request by marocchino**

### CODE REVIEW

**Comment by tfhartmann** [comment]
Hmmm can you elaborate on this feature?   I'm trying to figure out why we want an ELB added to ECS *instances* as opposed to adding them to the ECS *Service* which is what we typically do currently if we need to access exposed ports on the running containers...

**Comment by marocchino** [comment]
Sorry for late response.
Maybe it just lack of my understood. but, I want to trigger instances  auto scale with tasks condition.

Ideal plan is:
1. need to be scale
2. if lack of instance add instances
3. scale tasks

Because of we use fixed port in tasks, when tasks exceed maximum count of instances. scale will be failed forever. and I don't want that.

**Comment by joestump** [comment]
@tfhartmann I believe the ELBs in ECS do map to the host instances, which are the actual boxes running in the ASG. From there the [port mappings](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html) would map requests from the host to the container.

It's kinda confusing, but tasks will overload a host/container instance, which kicks off the ASG to scale up another host/container instance. At this point we have two instances running some number of tasks. A request comes into the ELB and needs to get to one of those tasks so it load balances across the host/container instances which then handle requests according to the port mappings locally.

**Review by joestump — APPROVED** [review]

**Comment by tfhartmann** [comment]
Hmmm I think I may not be understanding,  I can completely understand wanting to make the autoscaling group in the module more dynamic, but I'm not understanding how attaching a LB to the instance autoscaling group accomplishes that...

**Comment by tfhartmann** [comment]
Sorry to be dense guys!

**Comment by marocchino** [comment]
No problem at all. :)

**Pull request closed without merging**
